version: '3'

services:
  db:
    image: postgres
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command:
      - redis-server
  django:
    build: .
    ports:
      - "8000:8000"
    command:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
  celery:
    build: .
    command: celery -A social worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A social beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
