version: '3'

services:
  db:
    image: mdillon/postgis
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
    volumes:
      - .:/code
  web:
    build:
      context: ./
      dockerfile : Dockerfile
    command: gunicorn social.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
     - .:/code
     - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web
  celery:
    build: .
    command: celery -A social worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A social beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

