# Generated by Django 3.0.2 on 2020-01-21 06:44

from django.db import migrations, models
import django.db.models.deletion
import story.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20200121_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=story.models.image_path)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storys', to='user.User')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='likes', to='user.User')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
