# Generated by Django 3.0.2 on 2020-01-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_age'),
        ('story', '0003_auto_20200131_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyalarm',
            name='created_at',
        ),
        migrations.AddField(
            model_name='storyalarm',
            name='updated_ay',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storyalarm',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_alarm', to='user.User'),
        ),
        migrations.RemoveField(
            model_name='storyalarm',
            name='nickname',
        ),
        migrations.AddField(
            model_name='storyalarm',
            name='nickname',
            field=models.ManyToManyField(blank=True, null=True, related_name='nickname_alarm', to='user.User'),
        ),
    ]
