# Generated by Django 3.0.2 on 2020-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20200131_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
