# Generated by Django 3.0.2 on 2020-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
