# Generated by Django 3.0.2 on 2020-01-20 04:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_ay', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255, null=True)),
                ('nickname', models.CharField(max_length=14, null=True)),
                ('school', models.CharField(max_length=40, null=True)),
                ('intro', models.CharField(max_length=255, null=True)),
                ('bodytype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('personality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('hobby', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('height', models.IntegerField()),
                ('birth', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
