# Generated by Django 3.0.2 on 2020-01-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200121_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.AddField(
            model_name='user',
            name='userhate',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_userhate_+', to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='userlike',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_userlike_+', to='user.User'),
        ),
    ]
