# Generated by Django 3.0.2 on 2020-01-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200122_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userhate',
            field=models.ManyToManyField(blank=True, related_name='_user_userhate_+', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userlike',
            field=models.ManyToManyField(blank=True, related_name='_user_userlike_+', to='user.User'),
        ),
    ]
