# Generated by Django 3.0.2 on 2020-01-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200122_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userhate',
            field=models.ManyToManyField(blank=True, related_name='userhates', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userlike',
            field=models.ManyToManyField(blank=True, related_name='userlikes', to='user.User'),
        ),
    ]
