# Generated by Django 3.0.2 on 2020-01-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200123_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='type',
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_from_user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_to_user', to='user.User'),
        ),
    ]
