# Generated by Django 3.0.2 on 2020-01-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200123_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('f', '팔로잉'), ('b', '차단')], max_length=1),
        ),
    ]
