# Generated by Django 3.0.2 on 2020-01-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_relation_relation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['-relation_type']},
        ),
    ]
