# Generated by Django 3.0.2 on 2020-01-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
