# Generated by Django 3.0.2 on 2020-01-24 08:11

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200123_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.ImageField(default=user.models.rating_save, upload_to=''),
        ),
    ]
