# Generated by Django 3.0.2 on 2020-01-29 06:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200127_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_max_type', models.IntegerField(blank=True, null=True)),
                ('height_min_type', models.IntegerField(blank=True, null=True)),
                ('personality_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('bodytype_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_type_user', to='user.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
