# Generated by Django 3.0.2 on 2020-01-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200130_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontype',
            name='max_age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persontype',
            name='min_age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
