# Generated by Django 3.0.2 on 2020-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('l', '좋아요'), ('b', '차단'), ('h', '싫어요'), ('c', '채팅')], max_length=1),
        ),
    ]
