# Generated by Django 3.0.2 on 2020-02-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200210_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatting_list', to='user.User')),
                ('chttingwith', models.ManyToManyField(blank=True, null=True, related_name='chattingwith', to='user.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
