# Generated by Django 3.0.2 on 2020-02-17 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_user_fcmtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=32140),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
